### ISSUE TITLE
unpadding Node Buffer?

### ISSUE THREAD

**Issue by mickhansen** [brightcove/pkcs7#3]
This does not appear to work on Node buffers out of the box, what kind of converting do i need to do?

**Comment by dmlap** [comment]
pad and unpad are designed to work against [TypedArrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray). You can see an example of building a TypedArray from a buffer in the [cli module](https://github.com/brightcove/pkcs7/blob/b5ae9a981caad6564624f9a943b6b09b7173fc3f/lib/cli.js#L29).
